### PR TITLE
Change english

### PR DESCRIPTION
**Pull request by feliscatusmeows**

### CODE REVIEW

**Comment by feliscatusmeows** [comment]
meow

**Comment by feliscatusmeows** [comment]
meow

**Comment by feliscatusmeows** [comment]
frick i was merging to wrong brancj

**Comment by 0x150** [comment]
yeah no you are dead wrong in so many cases here bruh

see these comments below each constructor you marked as "not working"? these are mixins that do the logic because it cant really be done from the module itself

**Pull request closed without merging**
