### PR TITLE
📝・Some More Information about the Client

### PR DESCRIPTION
**Pull request by NotNoahDev**
Changes:
Added a Downloads tab 
&
File Size Tab for people wondering about file sizes

### CODE REVIEW

**Comment by ajl223** [comment]
I think the java percentage part isnt really useful and takes up too much space

**Comment by 0x150** [comment]
+ the downloads dont work, because we dont download from the releases

**Review by ajl223 — CHANGES_REQUESTED** [review]
I think the java percentage part isnt really useful and takes up too much space

**Review by 0x150 — CHANGES_REQUESTED** [review]
modify some unneeded things

**Comment by NotNoahDev** [comment]
> modify some unneeded things

Everything should be fixed, I think the file size tab would be necessary for some users before they download the source or a release.

**Review by ajl223 — CHANGES_REQUESTED** [review]
remove java since its useless and downloads unless you can get it to work, code size can stay as its a nice touch.

**Review by ajl223 — COMMENTED** [review]
is this the same as noah's? I think im blind

**Comment by NotNoahDev** [comment]
> remove java since its useless and downloads unless you can get it to work, code size can stay as its a nice touch.

yep should be fixed.

**Comment by ajl223** [comment]
can you include the change I suggested from #74?

**Comment by 0x150** [comment]
looks good for now

**Comment by NotNoahDev** [comment]
> can you include the change I suggested from #74?

I can soon, Just doing some work on my discord bot

**Pull request merged**
